server:
  applicationConnectors:
  - type: http
    port: 8080
  adminConnectors:
  - type: http
    port: 8081

localstack:
  serviceHost: ${LOCALSTACK_SERVICE_HOST:-localhost}
  servicePort: ${LOCALSTACK_SERVICE_PORT:-8080}
  serviceScheme: ${LOCALSTACK_SERVICE_SCHEME:-http}
