# Default values for Dropwizard projects.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: 257597320193.dkr.ecr.us-east-1.amazonaws.com/benvandenberg/thing-api
  tag: 1.0.1
  pullPolicy: IfNotPresent
service:
  name: thing-api
  type: ClusterIP
  appPort: 8080
  extAppPort: 80
  adminPort: 8081
  extAdminPort: 8081
  annotations:
    fabric8.io/expose: "true"
    fabric8.io/ingress.annotations: "kubernetes.io/ingress.class: nginx"
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 400m
    memory: 512Mi
probePath: /healthcheck
livenessProbe:
  initialDelaySeconds: 60
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1
readinessProbe:
  initialDelaySeconds: 30
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1
terminationGracePeriodSeconds: 10
