package com.thissideupsoftware;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.fasterxml.jackson.annotation.JsonInclude;
import lombok.*;

import java.util.UUID;

@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
@EqualsAndHashCode
@DynamoDBTable(tableName = "thing")
public class Thing {

    @DynamoDBAutoGeneratedKey
    @DynamoDBHashKey(attributeName = "id")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    UUID id;

    String data;
}
